#!/usr/bin/env bash
#
# sync-memory-index.sh — regenerate generated memory-bank index files.
#
# Sources (append-only, multi-agent safe):
#   .agents/memory-bank/registry/*.jsonl   stable IDs (one JSON object per line)
#   .agents/memory-bank/records/**         one file per record
#
# Targets (GENERATED — never hand-edit):
#   .agents/memory-bank/activeContext.md   from records/active/M*.md + risk.jsonl + scn.jsonl
#   .agents/memory-bank/progress.md        from records/progress/M*.md (sorted)
#   .agents/memory-bank/decisions.md       from registry/dec.jsonl
#   .agents/memory-bank/productContext.md   traceability tables (between markers)
#   .agents/plans/00-index.md              from records/{active,deferred,progress}/
#
# Usage:
#   scripts/sync-memory-index.sh           regenerate in place
#   scripts/sync-memory-index.sh --check   exit non-zero if any generated file differs (CI gate)
#
# Requirements: bash 4+, jq 1.6+, GNU coreutils (sort, mktemp).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MB="$ROOT/.agents/memory-bank"
REG="$MB/registry"
REC="$MB/records"
PLANS="$ROOT/.agents/plans"

require() { command -v "$1" >/dev/null 2>&1 || { echo "error: required command '$1' not found" >&2; exit 2; }; }
require jq
require sort
require mktemp

CHECK=0
if [[ "${1:-}" == "--check" ]]; then
  CHECK=1
fi

# Temporary working dir; on --check we diff against the real files.
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# ----------------------------------------------------------------------------
# Helper: read a jsonl file safely (skip empty lines / comments).
# ----------------------------------------------------------------------------
jsonl() { [[ -f "$1" ]] || return 0; grep -Ev '^\s*(//|$)' "$1" || true; }

# ----------------------------------------------------------------------------
# activeContext.md  <- records/active/M*.md + risk.jsonl + scn.jsonl
# ----------------------------------------------------------------------------
gen_active() {
  local out="$1"
  {
    echo "# Active context"
    echo
    echo "<!-- GENERATED by scripts/sync-memory-index.sh. Do not hand-edit. -->"
    echo "<!-- Source: records/active/M*.md + registry/risk.jsonl + registry/scn.jsonl -->"
    echo

    echo "## Active milestones"
    echo
    if compgen -G "$REC/active/M*.md" >/dev/null; then
      for f in "$REC"/active/M*.md; do
        local title; title=$(grep -m1 -E '^# ' "$f" | sed 's/^# *//')
        echo "- [${title:-$(basename "$f" .md)}]($(realpath --relative-to="$MB" "$f"))"
      done
    else
      echo "_(none)_"
    fi
    echo

    echo "## Known risks"
    echo
    echo "| ID | Severity | Status | Module | Summary |"
    echo "|---|---|---|---|---|"
    if [[ -f "$REG/risk.jsonl" ]]; then
      jsonl "$REG/risk.jsonl" | jq -r '
        "|"+.id+"|"+(.severity//"-")+"|"+(.status//"-")+"|"+(.module//"-")+"|"+(.summary//.title//"-")+"|"'
    fi
    echo

    echo "## Planned scenarios"
    echo
    echo "| ID | Status | Module | Title | Linked requirements |"
    echo "|---|---|---|---|---|"
    if [[ -f "$REG/scn.jsonl" ]]; then
      jsonl "$REG/scn.jsonl" | jq -r '
        "|"+.id+"|"+(.status//"-")+"|"+(.module//"-")+"|"+(.title//"-")+"|"+((.req//[])|join(", "))+"|"'
    fi
    echo
  } > "$out"
}

# ----------------------------------------------------------------------------
# progress.md  <- records/progress/M*.md (sorted by milestone number)
# ----------------------------------------------------------------------------
gen_progress() {
  local out="$1"
  {
    echo "# Progress log"
    echo
    echo "<!-- GENERATED by scripts/sync-memory-index.sh. Do not hand-edit. -->"
    echo "<!-- Source: records/progress/M*.md (one file per completed milestone) -->"
    echo

    if compgen -G "$REC/progress/M*.md" >/dev/null; then
      # Sort by the numeric part of MNN.md
      for f in $(ls "$REC"/progress/M*.md | sed -E 's/.*\/M([0-9]+)\.md/\1\t&/' | sort -n -k1,1 | cut -f2); do
        local title; title=$(grep -m1 -E '^# ' "$f" | sed 's/^# *//' | sed -E 's/^M[0-9]+ *— *//')
        local mnum; mnum=$(basename "$f" .md)
        echo "## ${mnum} — ${title}"
        echo
        echo "_Source: [$(realpath --relative-to="$MB" "$f")]($(realpath --relative-to="$MB" "$f"))_"
        echo
      done
    else
      echo "_(no completed milestones)_"
    fi
  } > "$out"
}

# ----------------------------------------------------------------------------
# decisions.md  <- registry/dec.jsonl
# ----------------------------------------------------------------------------
gen_decisions() {
  local out="$1"
  {
    echo "# Decisions (ADR log)"
    echo
    echo "<!-- GENERATED by scripts/sync-memory-index.sh. Do not hand-edit. -->"
    echo "<!-- Source: registry/dec.jsonl + records/decisions/DEC-###.md -->"
    echo

    if [[ -f "$REG/dec.jsonl" ]]; then
      # Sort by numeric DEC id
      jsonl "$REG/dec.jsonl" \
        | jq -r '. | "\(.id|ltrimstr("DEC-")|tonumber)\t\(.id)\t\(.status)\t\(.date)\t\(.title)\t\(.summary)\t\((.module//[])|join(", "))\t\((.body//"-"|sub("^\\.agents/memory-bank/";"")))"' \
        | sort -n -t$'\t' -k1,1 \
        | while IFS=$'\t' read -r _ id status date title summary module body; do
            echo "## ${id} — ${title}"
            echo
            echo "| Field | Value |"
            echo "|---|---|"
            echo "| Status | ${status} |"
            echo "| Date | ${date} |"
            echo "| Modules | ${module} |"
            echo "| Summary | ${summary} |"
            if [[ "$body" != "-" ]]; then
              echo "| Body | [${body}](${body}) |"
            fi
            echo
          done
    else
      echo "_(no decisions recorded)_"
    fi
  } > "$out"
}

# ----------------------------------------------------------------------------
# productContext.md traceability tables (between markers)
# ----------------------------------------------------------------------------
gen_product_tables() {
  local out="$1"
  {
    echo "| Requirement | Summary | Module | Domain models | Scenarios | Tests |"
    echo "|---|---|---|---|---|---|"
    if [[ -f "$REG/req.jsonl" ]]; then
      jsonl "$REG/req.jsonl" | jq -r '
        "|"+.id+"|"+(.summary//.title//"-")+"|"+(.module//"-")+"|"+((.domain_models//[])|join(", "))+"|"+((.scn//[])|join(", "))+"|"+((.test//[])|join(", "))+"|"'
    fi
    echo
    echo "| NFR | Category | Target | Module | Status |"
    echo "|---|---|---|---|---|"
    if [[ -f "$REG/nfr.jsonl" ]]; then
      jsonl "$REG/nfr.jsonl" | jq -r '
        "|"+.id+"|"+(.category//"-")+"|"+(.target//"-")+"|"+(.module//"-")+"|"+(.status//"-")+"|"'
    fi
  } > "$out"
}

patch_product() {
  local real="$MB/productContext.md"
  local tables="$1"
  # Re-emit: prose before BEGIN marker, generated tables, prose after END marker.
  # awk preserves newlines; we read the real file's prose (source of truth).
  awk -v tablesfile="$tables" '
    BEGIN { inblock=0 }
    /<!-- BEGIN GENERATED: traceability -->/ {
      print
      print "<!-- Traceability tables below are regenerated by scripts/sync-memory-index.sh. Do not hand-edit. -->"
      while ((getline line < tablesfile) > 0) print line
      print "<!-- END GENERATED: traceability -->"
      inblock=1
      next
    }
    /<!-- END GENERATED: traceability -->/ { inblock=0; next }
    inblock { next }
    { print }
  ' "$real" > "$TMP/productContext.md"
}

# ----------------------------------------------------------------------------
# plans/00-index.md  <- records/{active,deferred,progress}/
# ----------------------------------------------------------------------------
gen_plans_index() {
  local out="$1"
  {
    echo "# Plans index"
    echo
    echo "<!-- GENERATED by scripts/sync-memory-index.sh. Do not hand-edit. -->"
    echo "<!-- Source: records/{active,deferred,progress}/M*.md + plans/archive/ -->"
    echo

    echo "## Active"
    echo
    echo "| Milestone | Record |"
    echo "|---|---|"
    if compgen -G "$REC/active/M*.md" >/dev/null; then
      for f in "$REC"/active/M*.md; do
        local m; m=$(basename "$f" .md)
        echo "| ${m} | [$(realpath --relative-to="$PLANS" "$f")]($(realpath --relative-to="$PLANS" "$f")) |"
      done
    else
      echo "| _(none)_ | |"
    fi
    echo

    echo "## Deferred"
    echo
    echo "| Milestone | Record |"
    echo "|---|---|"
    if compgen -G "$REC/deferred/M*.md" >/dev/null; then
      for f in "$REC"/deferred/M*.md; do
        local m; m=$(basename "$f" .md)
        echo "| ${m} | [$(realpath --relative-to="$PLANS" "$f")]($(realpath --relative-to="$PLANS" "$f")) |"
      done
    else
      echo "| _(none)_ | |"
    fi
    echo

    echo "## Completed"
    echo
    echo "| Milestone | Record |"
    echo "|---|---|"
    if compgen -G "$REC/progress/M*.md" >/dev/null; then
      for f in $(ls "$REC"/progress/M*.md | sed -E 's/.*\/M([0-9]+)\.md/\1\t&/' | sort -n -k1,1 | cut -f2); do
        local m; m=$(basename "$f" .md)
        echo "| ${m} | [$(realpath --relative-to="$PLANS" "$f")]($(realpath --relative-to="$PLANS" "$f")) |"
      done
    else
      echo "| _(none)_ | |"
    fi
    echo

    echo "## Archived plan files"
    echo
    echo "| File |"
    echo "|---|"
    if compgen -G "$PLANS/archive/M-*.md" >/dev/null; then
      for f in "$PLANS"/archive/M-*.md; do
        echo "| [$(basename "$f")](archive/$(basename "$f")) |"
      done
    else
      echo "| _(none)_ |"
    fi
    echo

    echo "## Active plan files"
    echo
    echo "| File |"
    echo "|---|"
    if compgen -G "$PLANS/M-*.md" >/dev/null; then
      for f in "$PLANS"/M-*.md; do
        echo "| [$(basename "$f")]($(basename "$f")) |"
      done
    else
      echo "| _(none)_ |"
    fi
    echo
    echo "## Naming"
    echo
    echo "\`M-NN-short-topic.md\` — \`NN\` zero-padded plan number (not always equal to milestone number)."
  } > "$out"
}

# ----------------------------------------------------------------------------
# Run generation into TMP, then either write or diff.
# ----------------------------------------------------------------------------
gen_active        "$TMP/activeContext.md"
gen_progress      "$TMP/progress.md"
gen_decisions     "$TMP/decisions.md"
gen_product_tables "$TMP/_product_tables.md"
patch_product     "$TMP/_product_tables.md"
gen_plans_index   "$TMP/00-index.md"

declare -a targets=(
  "$MB/activeContext.md:$TMP/activeContext.md"
  "$MB/progress.md:$TMP/progress.md"
  "$MB/decisions.md:$TMP/decisions.md"
  "$MB/productContext.md:$TMP/productContext.md"
  "$PLANS/00-index.md:$TMP/00-index.md"
)

if [[ "$CHECK" -eq 0 ]]; then
  for pair in "${targets[@]}"; do
    dest="${pair%%:*}"; src="${pair##*:}"
    mkdir -p "$(dirname "$dest")"
    cp "$src" "$dest"
    echo "regenerated: $(realpath --relative-to="$ROOT" "$dest")"
  done
  echo "OK: indexes regenerated."
else
  drift=0
  for pair in "${targets[@]}"; do
    dest="${pair%%:*}"; src="${pair##*:}"
    if [[ ! -f "$dest" ]] || ! diff -q "$dest" "$src" >/dev/null 2>&1; then
      echo "DRIFT: $(realpath --relative-to="$ROOT" "$dest")"
      drift=1
    fi
  done
  if [[ "$drift" -ne 0 ]]; then
    echo "FAIL: generated indexes are out of sync. Run scripts/sync-memory-index.sh and commit." >&2
    exit 1
  fi
  echo "OK: generated indexes are in sync."
fi